# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1veGNp44Dfb5WrQ10M9_w_6l_mUneABE9
"""

# Given dictionary
app_data = {
    '436952197': [5, 'slots'],
    '478830284': [100, 'solitaire'],
    '501639931': [250, 'education'],
    '501641857': [1000, 'kids'],
    '513184827': [50, 'match']
}

# Filter apps with revenue > 100
filtered_apps = {app_id: data[1] for app_id, data in app_data.items() if data[0] > 100}

# Print the result
print("Apps with revenue above $100 and their verticals:")
for app_id, vertical in filtered_apps.items():
    print(f"App ID: {app_id}, Vertical: {vertical}")